name: go-skeleton pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    needs:
      - format-check
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Downloads
        run: go get -t ./...
      - name: Run Test
        run: go test ./...
  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run Format Check
        run: make check-format
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Copy Files
      run: |
           mkdir  artifacts
           cp go-skeleton artifacts/.

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
          name: go-skeleton
          path: artifacts
